---
testing: true # If true MQTT topics prefixed with TEST/
poll_rate: 12 # Rate (time in seconds) at which to poll for data
pwrcell:
  host: 127.0.0.1
  port: 5020
mqtt:
  client_name: pwrcell-ha
  host: homeassistant
  port: 1883
  username: mqtt-pwrcell
  password: XXXXXXXX
