---
testing: true # If true MQTT topics prefixed with TEST/
poll_rate: 60 # Rate (time in seconds) at which to poll for data
pwrcell:
  host: 192.168.0.2
  port: 5020
mqtt:
  client_name: pwrcell-ha
  host: homeassistant
  port: 1883
  username: mqtt-pwrcell
  password: XXXXXXXX
